[package]
name = "subtle"
# Before incrementing:
# - update CHANGELOG
# - update README if necessary by semver
# - if any updates were made to the README, also update the module documentation in src/lib.rs
version = "3.0.0-pre"
edition = "2024"
rust-version = "1.85.0"
authors = ["Isis Lovecruft <isis@patternsinthevoid.net>",
           "Henry de Valence <hdevalence@hdevalence.ca>"]
readme = "README.md"
license = "BSD-3-Clause"
repository = "https://github.com/dalek-cryptography/subtle"
homepage = "https://dalek.rs/"
documentation = "https://docs.rs/subtle"
categories = ["cryptography", "no-std"]
keywords = ["cryptography", "crypto", "constant-time", "utilities"]
description = "Pure-Rust traits and utilities for constant-time cryptographic implementations."
exclude = [".github", ".gitignore"]

[dev-dependencies]
rand = { version = "0.9" }
